[package]
name = "Boa"
version = "0.1.5"
authors = ["Jason Williams <jase.williams@gmail.com>"]
description = "Boa is a Javascript lexer, parser and Just-in-Time compiler written in Rust. Currently, it has support for some of the language."
homepage = "https://github.com/jasonwilliams/boa"
repository = "https://github.com/jasonwilliams/boa"
keywords = ["javascript", "compiler", "lexer", "parser", "js"]
license = "Unlicense OR MIT"
exclude = [".vscode/*", "Dockerfile", "Makefile", ".editorConfig"]
edition = "2018"

[dependencies]
gc = "0.3.2"
gc_derive = "0.3.2"
serde_json = "1.0"
rand = "0.5.5"
chrono = "0.4"

[lib]
name = "boa"
path = "src/lib/lib.rs"

# [[bin]]
# name = "js"
# path = "src/bin/bin.rs"