[package]
name = "Boa"
version = "0.1.0"
authors = ["Jason Williams <jase.williams@gmail.com>"]

[dependencies]

[lib]
name = "js"
path = "src/lib/lib.rs"

# [[bin]]
# name = "js"
# path = "src/bin/bin.rs"
