on: [pull_request]
name: Benchmarks
jobs:
  runBenchmark:
    name: run benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: jasonwilliams/criterion-compare-action@move_to_actions
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
